import { Providers } from "@/store/provider";
import "../../public/assets/scss/app.scss";
import "leaflet/dist/leaflet.css";
import "leaflet-control-geocoder/dist/Control.Geocoder.css";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import ErrorBoundary from "@/Common/ErrorBoundry";

export const metadata: Metadata = {
  title: "Rica-Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="ltr">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200&family=Nunito:ital,wght@0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <ErrorBoundary>
          <Providers>{children}</Providers>
          <ToastContainer />
        </ErrorBoundary>
      </body>
    </html>
  );
}
